### PR TITLE
feat: move to ESM first

### PR DESCRIPTION
**Pull request by userquin**
Right now we have:

imagen

Moving to ESM first:

imagen

### CODE REVIEW

**Comment by userquin** [comment]
we should also update node to 16 or maybe to 18...

**Comment by antfu** [comment]
I am not sure. In many usage the vite.config.ts might be a CJS. Requiring for dynamic import is not really worth it to me. And I don't actually mind to have "Masqureading CJS types"

**Comment by sxzz** [comment]
@antfu We need to copy `xxx.d.ts` to `xxx.d.mts`. The first dts is for CJS and the second one is for ESM, like [I done in unplugin](https://github.com/unjs/unplugin/commit/6b38ae33479a035321b930e5f498e9089a1dcb22)

**Comment by userquin** [comment]
@sxzz maybe we can have something CJS and ESM configured properly, somehting like this:
https://github.com/fabian-hiller/valibot/pull/12#issuecomment-1652016724

**Comment by antfu** [comment]
On the opposite, https://github.com/unjs/unbuild/pull/273, I thought that TS will look for the corresponding types based on the file name in node16

**Pull request closed without merging**
