### PR TITLE
fix: id resolving, fix #31, fix #25

### LINKED ISSUE #25: .vue module deleted when only update the style
## Reproduction

1. clone repository
2. install dependencies
3.  exec `npm run dev`
4. click  `./components/DiffEditor.vue` in `localhost:3000/__inspect`,  it's good
5. update `./components/DiffEditor.vue` ‘s’ `<style>`
```diff
...
<style lang="postcss">
.diff-added {
  @apply bg-green-400/15;
}
.diff-removed {
  @apply bg-red-400/15;
}
.diff-added-inline {
  @apply bg-green-400/30;
}
.diff-removed-inline {
  @apply bg-red-400/30;
}

+ .foo {
+  color: blue;
+  }
</style>
```
6. click  `./components/DiffEditor.vue` in `localhost:3000/__inspect`, **the CodeMirror** is empty
7. click refetch,  `./components/DiffEditor.vue` is not in the list anymore，You have to refresh the page to see it again

## debug

After changing only the style, I found that both  `./components/DiffEditor.vue`  and `./components/DiffEditor.vue?vue&type=style&index=0&lang.postcss` would be invalidated, only `./components/DiffEditor.vue?vue&type=style&index=0&lang.postcss` will be processed by resolveId, load, transfrom，`./components/DiffEditor.vue` not, so there is not `./components/DiffEditor.vue` in `transformMap`

```ts
const _invalidateModule = server.moduleGraph.invalidateModule
    server.moduleGraph.invalidateModule = function(...args) {
      const mod = args[0]
      if (mod?.id) {
        debug('invalidate module', mod.id)
        // here delete  `./components/DiffEditor.vue`
        delete transformMap[mod.id]
      }
      return _invalidateModule.apply(this, args)
    }
```

log

```log
// invalidate DiffEditor.vue and DiffEditor.vue?vue&type=style&index=0&lang.postcss
vite-plugin-inspect invalidate module D:/about-code/side-project/pr-project/vite-plugin-inspect/src/client/components/DiffEditor.vue +19s
  vite-plugin-inspect invalidate module D:/about-code/side-project/pr-project/vite-plugin-inspect/src/client/components/DiffEditor.vue?vue&type=style&index=0&lang.postcss +2ms
  vite:hmr [file change] components/DiffEditor.vue +11s
  vite:hmr [vue:update(style)] D:/about-code/side-project/pr-project/vite-plugin-inspect/src/client/components/DiffEditor.vue +19s
上午11:36:45 [vite] hmr update /components/DiffEditor.vue?vue&type=style&index=0&lang.postcss (x2)
  connect:dispatcher <anonymous> /__inspect : /__inspect/components/DiffEditor.vue?import&t=1649043405739&vue&type=style&index=0&lang.postcss +8s
  connect:dispatcher viteTimeMiddleware  : /__inspect/components/DiffEditor.vue?import&t=1649043405739&vue&type=style&index=0&lang.postcss +0ms      
  connect:dispatcher corsMiddleware  : /__inspect/components/DiffEditor.vue?import&t=1649043405739&vue&type=style&index=0&lang.postcss +1ms
  connect:dispatcher viteBaseMiddleware  : /__inspect/components/DiffEditor.vue?import&t=1649043405739&vue&type=style&index=0&lang.postcss +0ms      
  connect:dispatcher viteServePublicMiddleware  : /__inspect/components/DiffEditor.vue?import&t=1649043405739&vue&type=style&index=0&lang.postcss +0ms
  connect:dispatcher viteTransformMiddleware  : /__inspect/components/DiffEditor.vue?import&t=1649043405739&vue&type=style&index=0&lang.postcss +0ms 
  vite:load 0.10ms [plugin] /components/DiffEditor.vue?vue&type=style&index=0&lang.postcss +12s
  unplugin-vue-components:transformer D:/about-code/side-project/pr-project/vite-plugin-inspect/src/client/components/DiffEditor.vue +12s
  unplugin-vue-components:transform:component ^ (0) +12s
  unplugin-vue-components:decleration generating +12s
  vite:hmr [self-accepts] components\DiffEditor.vue?vue&type=style&index=0&lang.postcss +382ms
  vite:import-analysis 0.41ms [0 imports rewritten] components\DiffEditor.vue?vue&type=style&index=0&lang.postcss +12s
  vite:transform 9.08ms /components/DiffEditor.vue?vue&type=style&index=0&lang.postcss +12s
  vite:time 15.43ms /components/DiffEditor.vue?import&vue&type=style&index=0&lang.postcss +8s
```

### LINKED ISSUE #31: Can not find a file
### Describe the bug

init project with vite ,and then install **vite-plugin-inspect**.
click **/src/App.vue?vue&type=style&index=0&lang.css** at http://localhost:3000/__inspect/
will got **ENOENT: no such file or directory, open '/uls/Desktop/example/my-vue-app/src/App.vue'**
image

### Reproduction

none

### System Info

```Shell
mac Chrome last version
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by wulinsheng123**
### Description
fix：issues #31 #25

### CODE REVIEW

**Comment by antfu** [comment]
I would like to know more context about this

**Comment by wulinsheng123** [comment]
> I would like to know more context about this



> I would like to know more context about this

the link in **await fetch(resolved)** was sliced when called **clear** function to reloaded.

**Comment by nksaraf** [comment]
I saw an issue with these lines too in my PR #35. Is there a rason we were doing the `slice` before fetching?

**Comment by wulinsheng123** [comment]
> I saw an issue with these lines too in my PR #35. Is there a reason we were doing the `slice` before fetching?

yes., because slice

**Pull request merged**
