### PR TITLE
chore: switch using module 'path/posix' to 'path'

### PR DESCRIPTION
**Pull request by zheeeng**
As the Node official document says, `path/posix` is exposed at v15.3.0

### CODE REVIEW

**Comment by antfu** [comment]
We don't need `path/posix`, probably a mistake.

**Comment by zheeeng** [comment]
https://github.com/antfu/vite-plugin-inspect/blob/main/src/client/vite.config.ts#L2

This importing blocks development under node v14

**Comment by antfu** [comment]
Yes, I mean we could just use `path` there

**Comment by zheeeng** [comment]
PR updated

**Pull request merged**
